services:
  - type: web
    name: render-container
    env: docker
    repo: https://github.com/tkosht/render.git
    branch: main
    region: singapore
    plan: free
    rootDir: .
    dockerfilePath: docker/Dockerfile.cpu
    dockerContext: .
    dockerCommand: /home/devuser/.local/bin/poetry run bash bin/run_demo.sh
    numInstances: 1
    envVars:
      - key: user_name
        value: devuser
      - key: group_name
        value: devgroup
      - key: PORT
        value: 8501

