version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.cpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: $pj_name.app
    container_name: $pj_name.app
    tty: true
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    sysctls:
      - net.core.somaxconn=$somaxconn
      - net.ipv4.tcp_syncookies=0
    ports:
      - "8502:8501"   # streamlit

